### ISSUE TITLE
In spam module, log the message that triggered the auto-mute

### ISSUE THREAD

**Issue by Julien00859** [DigitalPulseSoftware/NotaBot#41]
Hi,

We are using Not a Bot on our server with quite some success, the recent spam module is an handy addition. From time to time, there are false-positives and a legit member gets wrongly auto-muted; e.g. a member sending multiple pastebin-like links, one per file he is working on, to ask for assistance. The logged message "`<@x>` had been auto-mute because of spam in `<#y>`" is very nice because it gives us the opportunity to look at the logs and verify which message triggered the auto-mute, then our policy is either kick the spammer or unmute the unfortunate member.

Because we are moderating a quite busy server (10k+ members), our logs are quite dense and it is not always easy to determine which message triggered the auto-mute. My suggestion is to add the message that triggered the auto-mute (the one whose score exceeded the configured threshold, if it is easy to do) in the logs to ease our job. Maybe there could be an unmute button next to the message.

Regards,

**Comment by Equinox4** [comment]
Perhaps we should add the possibility to configure the link score for some channels?
e.g reduce the weight of the links score in a technical channel that can only be joined with the appropriate role, this would allow users to send multiple links easier without lowering the detection level too much.

**Comment by Julien00859** [comment]
See also #49

**Comment by Elanis** [comment]
Done, should be closed :)
