### ISSUE TITLE
Message module - addreply should have a configuration to forward ping

### ISSUE THREAD

**Issue by Elanis** [DigitalPulseSoftware/NotaBot#45]
When registering a command with !addreply, we shoud be able to have an option forward ping or message reply from trigger.

Example:
![image](https://user-images.githubusercontent.com/7013446/163356515-9e3283a1-01d0-4dfb-9888-49beb5b46fc8.png)

It would be nice to have the bot answering directly to the answered message ("Test") if needed as an option

**Comment by andrelec1** [comment]
same with `@xxx !foo`
