### ISSUE TITLE
Add `userinfo` command to get user information

### ISSUE THREAD

**Issue by Elanis** [DigitalPulseSoftware/NotaBot#47]
In the process to stop using Dyno on "Not a name" server, we will need this command to be added in Not A Bot.

`userinfo` log as many as possible information about the current user. Example:
![image](https://user-images.githubusercontent.com/7013446/167397014-b6b302cf-6f83-4e4e-a70c-d47c552bab37.png)

If some more information are available and useful in a moderating context, they can be added to the embed as well.

**Comment by Julien00859** [comment]
Of them the info I use the most are (1) the user discord account creation date and (2) the date the user joined the server.

**Comment by Equinox4** [comment]
I am working on it and will probably keep the same information as TeXit.
