### ISSUE TITLE
Add `prune X` command to remove last X messages in the current channel

### ISSUE THREAD

**Issue by Elanis** [DigitalPulseSoftware/NotaBot#48]
In the process to stop using Dyno on "Not a name" server, we will need this command to be added in Not A Bot.

 `prune X` command is used to remove last X messages in the current channel. It should remove the command message as well (but not counted in the `X` counter.

**Comment by Julien00859** [comment]
I would like a command that is `prune <message-id>` where message-id is a message identifier in the current server, e.g. `358924179954860033-860919802435469353` for https://discord.com/channels/323076998576603137/358924179954860033/860919802435469353. This command would delete all the messages starting at `<message-id>` included.

**Comment by Elanis** [comment]
This Issue can be closed thanks to #80
