### ISSUE TITLE
Offer a config for the preffix or use @notabot as a prefix

### ISSUE THREAD

**Issue by Julien00859** [DigitalPulseSoftware/NotaBot#52]
It is annoying that multiple bots are using the same `!` as prefix. There are places where NaB was added just for a very few modules and the admins wanted to replace `!` by something else for NaB.

I'm suggesting to make it configurable and to add another hard-coded prefix. If the first word is a mention to the bot, it could be considered as a prefix i.e. you could do `@notabot enable raid`

![image](https://user-images.githubusercontent.com/8208953/168880277-7a4ad0c0-7a95-4bec-b4fd-9a9e4eb0a2c8.png)

![image](https://user-images.githubusercontent.com/8208953/168880409-dd32061c-ddf5-457c-a20d-a23cdd0eaa90.png)

**Comment by Julien00859** [comment]
I am told that the mention stuff I'm talking about exist already 👀

**Comment by SirLynix** [comment]
Done, you can use `serverconfig` module to configure this.
![image](https://user-images.githubusercontent.com/3002461/168978526-8fb4ebd4-937b-4930-8126-9a5ce549e589.png)
